services:
  postgres:
    container_name: postgres-sql
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: java_auth
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgres/data
    networks:
      - infinity-network
  infinity-app:
    container_name: infinity
    image: spring/infinity
    ports:
      - "8088:8080"
    networks:
      - infinity-network

volumes:
  postgres:

networks:
  infinity-network:
    driver: bridge